### ISSUE TITLE
Oportunidades en el código legado

### ISSUE THREAD

**Issue by chuucks** [eventloop/platicas#104]
### Presentación
Hola comunidad de **Eventloop** el año pasado tuve la oportunidad de compartir una charla con ustedes sobre _experiencias de implementación de tecnologías modernas en corporativos_, en esta ocación me gustaría compartir la contraparte: _experiencias con código legado (ventajas y desventajas)_.

### Sumario
En la actualidad los jovenes, despreciamos el código legado, sentimos que nos "estancamos" al no estar utilizando las "últimas tecnologías".

Nos hace falta ver las oportunidades que estas asignaciones traen, aprovecharlas nos podría convertir en un heroe en nuestra compañía.

### Agenda
1. Código legado en empresas
1.1. ¿Por qué existe?
1.2. Desventajas
1.3. Riesgos
2. Oportunidades 
2.1. Modificaciones importantes
2.2. Aprendizaje y experiencia
2.3 . Confianza Ganada
3. Refactorización vs Reconstrucción
3.1 Ventajas y riesgos de la refactorización
3.2 Buenas prácticas de refactorización
3.3. Ventajas y riesgos de la reconstrucción
3.4. Buenas práctica de reconstrucción
4. Experiencias personales con código legado
4.1. Situaciones a las que me enfrenté
4.2. Cómo ataqué el problema
4.3. Resultados

### Fecha
En Junio o Julio me viene bien.
_Ahora vivo en Guadalajara, una confirmación anticipada me ayuda a planear mi traslado._

### Tipo de charla
Experiencias aprendidas

### Información personal
name: Carlos Salazar
twitter: https://twitter.com/chuucksc
portfolio: https://carlos-salazar.com/
blog: https://codesolt.com/
pic: https://carlos-salazar.com/img/about.jpg
bio: Java Expert en **HP**, fundador de **Codesolt** y co-organizador de **Java Guadalajara**.
experienca: Speaker en el meetup mensual de Java en Montreal, Canada (http://www.montreal-jug.org/meetup/spring-security-oauth/)
ejemplo: Platzi Conf 2017 (https://www.youtube.com/watch?v=vGsMoD0hLUc)
​

**Comment by Sparragus** [comment]
Este tema me gusta mucho. Recuerdo la presentación que @chuucks dió el año pasado y fue muy buena. Tiene mi LGTM para que de la plática en junio. Que creen los demas?

**Comment by chuucks** [comment]
Muchas gracias @Sparragus  ^^

**Comment by tzkmx** [comment]
Suena muy bien porque muchas veces los juniors no tienen perspectiva de los riesgos que implican cosas como "reescribir todo en el último framework".

**Comment by chuucks** [comment]
Un pequeño post sobre las generalidades de este tema en mi blog:
https://codesolt.com/revisiones/codigo-legado/

**Comment by chuucks** [comment]
Hola @Ikana cuenten con ello :)

**Comment by chuucks** [comment]
Hola equipo de Eventloop, encuentren la presentación [aquí](https://drive.google.com/open?id=16RW7kUZYk0zx9O8H0bmsAioJlvMJOCYe)

Entonces seguro el 6 de Junio? Para confirmar mi viaje :P

**Comment by Ikana** [comment]
Si ya esta todo listo

Am Mi., 30. Mai 2018 um 01:02 Uhr schrieb Carlos E. Salazar <
notifications@github.com>:

**Comment by chuucks** [comment]
Gracias, viaje confirmado. Nos vemos el 6 de Junio! ;)

**Comment by chuucks** [comment]
Hola Eventloop family, 

hay que llevar la presentación en usb/pc/nube mañana?

Saludos

**Comment by Sparragus** [comment]
Si. Puedes presentar en tu compu pero te sugiero la lleves en un USB en PDF
por si acaso
