### ISSUE TITLE
React Dropzone Uploader

### ISSUE THREAD

**Issue by kylebebak** [eventloop/platicas#126]
### Sumario
Hace poco hice mi primer plugin de React, [React Dropzone Uploader](https://react-dropzone-uploader.js.org/).

Es un HTML5 dropzone y uploader que es sencillo de usar y muy customizable.

Me gustaría enseñar cómo funciona RDU, y enseñar unas buenas prácticas para hacer un plugin de React, y para hacer plugins en general.

### Outline

- Demostrar funcionalidad
  + Ejemplos en vivo
  + Ejemplos en producción
- Describir API
  + Plugins tienen que lograr 2 objetivos que muchas veces están opuestos
    * ser sencillos e intuitivos
    * ser altamente customizables
- Cómo hacer un plugin customizable
  + Diseño modular
  + CSS y CSS in JS
  + Component injection
- Cómo documentar tu plugin
  + Incluir props y descripción de API
  + Incluir ejemplos!
  + Implementación: Docusaurus, GitHub Pages, js.org
- Cómo escribir pruebas básicas

### Bio
~~~yaml
name: Kyle Bebak
url: https://github.com/kylebebak
pic: http://dronfelipe.com/images/img/face.png
bio: "Pythonista/React dude, ciclista kamikaze"
~~~

### Cuándo
En enero!

**Comment by Sparragus** [comment]
Creo que enero puede ser un evento de inventos y side-projects. Yo quiero dar una de google spreadsheets  como DB y prototyping. Kyle tiene algo que creo. Podemos buscar una mas.

Que creen que enero sea un mes de inventos/side-projects?

**Comment by kylebebak** [comment]
A mí me late!
