### ISSUE TITLE
Identity and Access Control for Modern Web Applications using Auth0

### ISSUE THREAD

**Issue by mercadoalex** [eventloop/platicas#131]
El manejo de identidad y autenticación no es un tema trivial,  no solo dentro del desarrollo JS si no dentro de todo el mundo del desarrollo software, este puede llegar a ser muy complejo debido a los diversos protocolos y  heterogéneos escenarios que las empresas suelen manejar.

Con Auth0 podemos solventar este tema en nuestras aplicaciones web ya sean en JS vanilla, Vue, Angular,  React u otro.

1. Presentar la problemática, con problemas de seguridad que le han  pasado a muchas empresas.
2. Presentar la solución. 
3. Demo 
4. Cerveza 

Estaría chido que fuera para el evento  de marzo.

name: Alejandro Mercado 
url: hhttps://twitter.com/alexmarket
pic: https://drive.google.com/file/d/1lOilZVx8egbfZxUy3p7ZOohscgHmEorF/view?usp=sharing
bio: Auth0 Ambassador , IoT enthusiast, HTML5 + JS organizer

**Comment by Ikana** [comment]
Hola, crees poder dar la platica en el proximo evento?

**Comment by mercadoalex** [comment]
Si con gustp.
