### ISSUE TITLE
3 historias de burocracia en un ambiente corporativo

### ISSUE THREAD

**Issue by chuucks** [eventloop/platicas#67]
# 3 historias de burocracia en un ambiente corporativo 
### Justificación
Las empresas tradicionales y los grandes corporativos ponen especial atención a los temas de seguridad e implementación de las tecnologías que utilizan para el desarrollo de su Software. En este sentido, se vuelve complicado el uso y apertura a tecnologías modernas, que más allá de perjudicar, beneficiarían al negocio, la operación y la innovación dentro de la empresa. Qué retos hay que superar para lograr la implementación de nuestras propuestas?

### Sumario
Compartiré mi experiencia y aprendizaje en cuanto a las dificultades que hay que enfrentar al proponer la implementación de nuevas tecnologías en corporativos.

### Outline
**1. Presentación**
- Breve relato de mi carrera y experiencia
- Muestra de algunos ejemplos de mi trabajo y proyectos

**2. Planteamiento**
- Desarrollo de Software en ambientes corporativos
- Restricción a nuevas tecnologías en ambientes corporativos
- Ventajas e impacto de nuevas tecnologías en ambientes corporativos

**3. Implementación y Resultados**
- Historia 1: Implementación de Git con GitLab
- Historia 2: Implementación de Python para procesamiento de archivos
- Historia 3: Implementación de Js para actualización de componentes sin acceder a controllers de Java

**4.- Conclusiones**
- Beneficios de las implementaciones
- Experiencias y aprendizaje

## Fech
Miércoles 5 de Abril de 2017

## Acerca de mí
**Nombre**: Carlos Salazar (Chuuck)
**URL**: [Portafolio](https://codesolt.com/)
**Blog**: [Blog](https://codesolt.com/blog)
**Pic**: [Dando una charla Central](https://codesolt.com/assets/img/resume/who-we-are-image-3.jpg)
**Bio**: "Ingeniero de Software por la UNAM, Arquitecto de Software en TotalPlay y fundador de Codesolt. Antes, desarrollador de Software en Avon, Scotiabank y escritor en Platzi."
**Ejemplo de charla**: [Clase de Scrum en Platzi](https://platzi.com/clases/comunidad-platzi/concepto/estrategia/ventajas-de-usar-scrum/material/)
**mail**: carlos.salazar@codesolt.com

### Adicional
Gracias por leer este ISSUE (propuesta de charla), espero poder compartir con la comunidad muy pronto, soy fiel seguidor de Javascript Mx. Un especial saludo! :)

**Comment by jeduan** [comment]
Hey @chuucks.

Antes que nada perdón por el retraso enorme. Hemos tenido esta propuesta bastante presente, y apreciamos mucho lo detallado que lo escribiste y la intención de compartir tu experiencia con la comunidad de Eventloop.

Creo que lo que me gustaría preguntarte es qué es lo que esperarías que se lleve la gente al terminar la plática, si te estás imaginando un público que apenas va a tener su primer trabajo, y platicarles las cosas que se viven en el mundo real o más un programador avanzado pero que no ha usado Spring.

Quizá lo que veo que quieres platicar es más una comparativa entre Single Page Apps vs aplicaciones que renderean todo el HTML para cada aplicación?

Sigamos cocinando esta plática 😄

**Comment by chuucks** [comment]
Hola @jeduan gracias por la respuesta.

El objetivo de la charla es justo que los asistentes de Event Loop (de cualquier nivel de experiencia) aprecien como Js en el cliente se lleva bastante bien con frameworks MVC de otros lenguajes, como Java con Spring. Y que vean cómo podemos aprovechar las cualidades de Js junto con estos otros lenguajes para crear aplicaciones Web del lado del cliente bastante poderosas.

De tal modo que los programadores Js estén abiertos a la posibilidad de integrarlo con otros lenguajes y los programadores No JS estén abiertos a complementar sus modelos MVC con Js. Además de tener una idea general de cómo explotarlo.

Creo que se podrá aprovechar un poco mejor por los programadores de nivel medio en adelante, pero en general tengo pensado revisar los conceptos desde cero para dar un mejor contexto de la situación (tomando en cuenta que la especialidad en eventloop no es Java), aprovechando para dar algunos ejemplos puntuales de cómo llevar a cabo estás implementaciónes.

Gracias y sigo por aquí para seguir cocinando esta charla! :)

**Comment by Sparragus** [comment]
Dude, el jueves que de la semana que viene va a haber evento. Estaría chido conocerte! :D

**Comment by chuucks** [comment]
Ahí nos vemos! @Sparragus ;)

**Comment by chuucks** [comment]
Issue actualizado @jeduan
