### ISSUE TITLE
Flow

### ISSUE THREAD

**Issue by Ikana** [eventloop/platicas#79]
### Sumario

Platicare sobre flow un sistema de tipado estático para JS, con inferencia de tipos, tipos union, tipos intersección y que que aunque puede ser usado stand alone, es desarrollado por un equipo interno de facebook para facilitar el desarrollo de todo su ecosistema (react, react-native, graphql ...)

### Outline

1. Tipos en vanilla JS
2. Pequeña historia sobre flow
3. Tipos en flow
4. Inferencia de tipos
5. Tipos union
6. Tipos intersección
7. Features avanzados de flow
8. Libreria standart de flow
9. Liberias externas y flow-typed
10. Pequeño boilerplate

**Comment by Sparragus** [comment]
Quiero aceptar tu plática pero aun no siento que hemos aterrizado bien el outline. Es decir, el tema es buenísimo, pero tenemos que trabajar el outline. El otro asunto que veo es que estas tratando de cubrir demasiado para una platica de 20 minutos. No tienes que explicarnos TODO de flow. Basta con explicarnos de qué trata Flow suficientemente como para entender de que va y que si nos interesa podamos seguir investigando el tema por nuestra cuenta.

He visto muchas pláticas que tratan de ir a profundidad y lo que hacen es fallar miserablemente por que en 20 minutos no se puede. Usualmente cuando necesitas mas de 20 minutos para explicar es por que no se domina el tema.

Pero te conozco y se que sí entiendes de que va el asunto con Flow. Se que puedes dar esta plática.

Entonces...

Antes de hablar de tipos en vanilla JS, y mucho antes de hablar de flow, tienes que hablar sobre el problema: JS no es un lenguaje de programación estaticamente tipado y por lo tanto las herramientas que usamos para programar no pueden inferir sobre lo que tratamos de hacer en el código para sugerir autocompletados o avisarnos de posibles o seguros errores.

Una vez ya nos has contado el problema, puedes comenzar a explicar por qué es un problema. Es decir, a hablar de como son los tipos de variables en JS. 

Ya entendemos el asunto con los tipos de variables en JS. Ya estamos listos y ansiosos para que nos vueles la cabeza con esta magia que nos vienes a halar y que se llama Flow.

BOOM! Autocomplete. Sugerencias. Warnings. Seguridad. Errores antes de correr el codigo. WHOA! Tell me more.

Ya nos diste el sneak peak de qué es Flow. Ahora cuéntanos como funciona.

El primer ejemplo puede ser con una función que se supone que suma numero pero le tratas de pasar un `'2'`. Danos algo simple. Apenas vamos comenzando.

Okay. Ya vimos los errores. Ahora enseñame como puedo ver ese autocompletado. Como asignamos el tipo de un parametro de una función.

Luego de eso enseñame como puedo definir mis propios tipos.

Con todo eso ya tenemos la intro a Flow. Ya estamos listos para más. Pero ya no nos queda tiempo! D:

Puede finalizar haciendo una breve mención de flow-typed. Eso esta bien chido y le va a later mucho a la banda. 

Y ya!

Si te das cuenta no hice ninguna mención de:
- Tipos union
- Tipos intersección
- Features avanzados de flow
- Libreria standart de flow
- Pequeño boilerplate

Todo lo que dejaste afuera, deja que la gente te haga las preguntas. Lo más probable es que el 95% de la audiencia no entienda esas partes que dejamos afuera. Ni si quiera habían escuchado de Flow.

En resumen:

1. El problema
2. Sneak peak a la solución: Flow y sus mind-blowing features
3. Inferencia de tipos (Aprovechar flow sin hacer nada)
4. Asignar tipos a los parametros de funciones. (Aprovechar Flow más aun usando los tipos nativos de JS)
5. Crear nuevos tipos.
6. Flow-typed
7. Pregunta.

Recuerda, solo tienes 20 minutos.

Como lo ves?

cc. @jeduan Qué crees?

**Comment by Sparragus** [comment]
Btw, fuertemente te sugiero y te reto a que no codees nada en vivo. Soy fan de los screencasts. Si quieres codear en vivo, trata de dejarlo para el final y solo si te queda tiempo.

**Comment by Ikana** [comment]
Tienes razon me emocione con tanta info.
Que te parece este nuevo outline:

1. El mitico Undefined is not a function
2. Tipos en JS y Tipos en otros lenguajes
3. Como los tipos te protegen de errores tontos
5. Killer features de flow(muy general inferencia de tipos, como los tipos fluyen ;)..)
6. Como solo agregar la anotación a un archivo existente, te da warnings utiles (5 ejemplos simples)
7. Preguntas

Creo fui un poco al otros extremo y en ves de hacer flow el tema principal, lo cambie mas a los tipos, porque pienso los equipos que desarrollaron la herramienta se dieron cuenta que no puedes desarrollar aplicaciones grandes y con un equipo de muchas personas sin tipos

**Comment by Sparragus** [comment]
Mucho mejor :)

**Comment by Sparragus** [comment]
Aceptada! :D

**Comment by Sparragus** [comment]
Hey dude! Listo para hoy? Tienes alguna pregunta sobre el evento? Quieres ayuda con tu presentación? Quieres que le echemos un vistazo? Déjanos saber. :)

**Comment by Ikana** [comment]
Pues no, ya tengo todo listo nos vemos al rato!
