### ISSUE TITLE
No ha sido fácil empezar a desarrollar

### ISSUE THREAD

**Issue by vaz-developer** [eventloop/platicas#93]
# **Sumario**
Llevo poco en el mundo de desarrollo y poco a poco me he dado cuenta de muchas cosas de lo que les quiero platicar.
Existen diferentes personalidades dentro de este mundo. Algunas personas casi no hablan y otras son mas extrovertidas. Algunas personas suelen ser mas centradas en las tareas  y otras  se atreven a compartir con el mundo lo que han ido aprendido. 
Yo soy como estas ultimas, cuando descubrí que ahora del lado del cliente se pueden hacer mas cosas que hace diez años, mis ganas de gritar al mundo(o al menos en mi mundo laboral) que había descubierto "esa magia" que podía ahorrarnos algunas horas de código fue inmensa.
Al final no sabia si seria bien recibido por las demás o no, y me di cuenta que esa solución tenia mas preguntas que aun no había visto, pero eso no importaba, acababa de descubrir otro camino: 
Este nuevo camino, quiero creer que es como la vida, sabes que un camino es mejor que otro pero no sabes que tendrá en medio, habrá que ir caminando y resolviendo a la vez lo que se vaya presentando.

# **Outline**
1.- Mis inicios como desarrolladora
     - ¿Donde quedó lo fashion?
     - ¿En tan solo 5 meses?

2.- Pero tu no eres ingeniera...
     - Prejuicios de carreras
     - ¿Tiene algo de raro ser mujer y pensar?
     -¿Sabes programar, verdad?
     -Vas empezando, te falta mucho por aprender

3.- Es que hay tanto, ¿por donde empiezo?
     - La importancia de pedir ayuda y buscar un mentor
     -Y ¿que pasa con las preguntas "obvias"?

4.- Aprendizajes de una desarrolladora junior
     - Juzga por ideas no por años
     -Las minorías también tienen algo que decir
     -Las buenas ideas provienen de cualquier parte

```yaml
name: Evelyn Vázquez
url: https://twitter.com/HeavenVaz
pic: https://twitter.com/HeavenVaz
bio: Empezando a conocer el mundo mágico del desarrollo
```

**Comment by Sparragus** [comment]
Gracias por compartir con la comunidad. Dar plática es la mejor forma de contribuir :) Gracias!
