### ISSUE TITLE
Exploración, Debugueo y Pruebas de web APIs usando Requester

### ISSUE THREAD

**Issue by kylebebak** [eventloop/platicas#99]
### Sumario
Crear y consumir web APIs es fundamental para desarrollo web y mobile. Existen varios clientes HTTP que ayudan con esto. A grandes rasgos se dividen entre clientes GUI como Postman, Insomnia y Paw, y clientes CLI como cURL y HTTPie.

[Requester](http://requester.org/) es un cliente HTTP para Sublime Text. Combina elementos de managed UI propios de clientes GUI como colecciones, historial de peticiones, env vars y pruebas automatizadas, con la ligereza y rápidez de clientes CLI. Todo se trabaja con texto, lo cual hace trivial compartir y versionar colecciones de peticiones. Su sintaxis es poderoso y muy bien documentado.

Me gustaría enseñar cómo Requester se puede usar para agilizar la exploración y creación de web APIs.

### Outline
- Instalación
- Features básicos y sintaxis
  + Request Body, Query Params, Custom Headers, Cookies
  + Variables de ambiente, authentication
  + Downloads, uploads
  + Parser y sintaxis (Requests)
- UI y UX
  + Colecciones de peticiones y navegación
  + Pestañas de respuesta
  + Historial de peticiones
- Pruebas
  + Test Runner
    + Sintaxis
    + JSON Schema
    + Integración con build process (generar scripts de pruebas)
  + Métricas (Benchmarking Tool)
- Portabilidad y Equipos
  + Importar de/exportar a cURL
  + Exportar a HTTPie
  + Versionando y compartiendo colecciones
    + `env_file` separado
- Caso de estudio: Twitter API
  + Extensiones a Requester, `requests-oauthlib`
  + Explorando hyperlinked APIs (HATEOAS)

### Bio
```yaml
name: Kyle Bebak
url: https://github.com/kylebebak
pic: http://dronfelipe.com/images/img/face.png
bio: "Pythonista/React dude, ciclista kamikaze"
```

### Cuándo
Octubre si se puede.

**Comment by Ikana** [comment]
Hola, si vi tu demo en le eventloop pasado y me parecio muy cool la idea, una gran porcentaje de nuestra comunidad usa atom o vs code, has pensado portearlo a eses editores?

**Comment by kylebebak** [comment]
Espero que todos estén bien después del sismo. Estuve en el centro y se sintió gacho...


No me sorprende la popularidad de Atom y VS Code, son muy buenos y sus developer APIs están en JS.

No tengo planes por el momento de portearlo a otro editor, sería un trabajo grande, para alguien con buen nivel haciendo plugins de Atom/VS Code. Me encantaría si alguien quisiera hacerlo, ayudaría con mucho gusto.

Dicho esto, creo que la plática sería bastante relevante y valiosa de todas formas. Requester está diseñado para reemplazar GUI HTTP clients como Postman, Insomnia y Paw. Sé que mucha gente en Eventloop trabaja con web APIs, y me imagino que muchos usan una de estas apps. Tanto ellos como los que no han usado HTTP clients podrían sacar mucho provecho a Requester. Al final del día es cambiar entre Atom/Sublime en vez de Atom/Postman.

Su test runner es poderoso y usa JSON Schema, un lenguaje que está hecho a la medida para describir web APIs, y que será algo nuevo para muchos. Finalmente, puede servir como ejemplo a los que quieren implementar plugins para Atom/VS Code/Sublime.

**Comment by Ikana** [comment]
Hola estamos bien gracias  ¿crees poder en noviembre o en diciembre?, es probable que abramos el proximo eventloop a iniciativas que quieran ayudar al sismo

**Comment by kylebebak** [comment]
Hola, qué bueno que todos estén bien.

En noviembre me encantaría. Me late la idea de hacer proyectos para ayudar con lo del sismo, a ver qué propone la gente.

Gracias y saludos

**Comment by Ikana** [comment]
Hola puedes presentar el 8 de noviembre?

**Comment by kylebebak** [comment]
Sí, me late. Allí nos vemos el 8 de noviembre, saludos
